### ISSUE TITLE
Refresh token issue

### ISSUE THREAD

**Issue by webtoolbox** [googleads/googleads-perl-lib#23] opened 2018-01-30 23:55 UTC
Hi Nadine,

Github says "You can't comment at this time" when I try to reply to the existing issue, so I had to open a new issue to contact you. I think you need to modify the permissions in the github repo.

Here are the answers to your questions:

What version of the library were you using before 5.0.0?

201702

Were you putting everything including the refresh token into adwords.properties?

Yes.

Did you make any other changes at the same time?

No.

Did you change API versions at the same time?

I'm not sure what you mean by this question. 

For example:
use Google::Ads::AdWords::v201702::UploadConversion;
changed to
use Google::Ads::AdWords::v201710::UploadConversion;

**Comment by sundquist** [comment] 2018-01-31 14:17
I'm marking this as a duplicate of #22 so we can continue the conversation over there.

**Closed by sundquist** 2018-01-31 14:17 UTC
Labels: duplicate
